version: '3.8'

services:
  app:
    image: 'noxway/noxway:0.0.1'
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./noxway/certs:/app/certs
      - ./noxway/config:/app/config
      - ./noxway/log:/app/log
    environment:
      JWTSECRET: "v4eAZlM0w9tpWx7SpTklWTRUCXyI8p"
      DATABASE: "noxway:${NOXWAY_DB_PASSWORD}@tcp(db:3306)/noxway?charset=utf8&parseTime=True&loc=Local"
    restart: unless-stopped
    depends_on:
      - db
   

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: change_me_please
      MYSQL_DATABASE: noxway
      MYSQL_USER: noxway
      MYSQL_PASSWORD: "${NOXWAY_DB_PASSWORD}"
    volumes:
      - ./noxway/db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  db_data:


